name: 'Sync markdown to Notion'
description: 'Syncs .md files in a github repo to a Notion page'
inputs:
  NOTION_ACCESS_TOKEN:
    description: 'Access token to access Notion API.'
    required: true
  NOTION_PAGE_ID:
    description: 'The page ID where the data will be synced. Contents and subpages will be replaced. Make sure the access token has been given access to the page.'
    required: true
  WIKI_CHECKOUT_PATH:
    description: 'The path where the wiki of the repo is checked out. If not set, wiki will not be exported to Notion.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'