name: 'Sync markdown to Notion'
description: 'Syncs .md files in a github repo to a Notion page'
inputs:
  NOTION_ACCESS_TOKEN:
    description: 'Access token to access Notion API.'
    required: true
  NOTION_ROOT_PAGE_ID:
    description: 'The page ID where the data will be synced. Make sure the access token has been given access to the page.'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'